-- =============================================================
-- Reels Generator — Supabase schema (Source of Truth)
-- Apply this in Supabase Dashboard -> SQL Editor
-- Safe to re-run (idempotent)
-- =============================================================

-- Required for gen_random_uuid()
create extension if not exists "pgcrypto";

-- -------------------------------------------------------------
-- 1. Tables
-- -------------------------------------------------------------

-- Videos Table: Root of the session.
-- Note: gcs_uri stores the relative path within the 'reels-videos' bucket.
create table if not exists videos (
    id uuid primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    filename text not null,
    status text not null,
    gcs_uri text not null,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);

-- Transcripts Table: Stores Gemini transcription output.
create table if not exists transcripts (
    id uuid primary key default gen_random_uuid(),
    video_id uuid references videos(id) on delete cascade,
    full_text text not null,
    -- Word-level timestamps: JSONB array of {text, start, end}.
    words jsonb,
    created_at timestamp with time zone default current_timestamp
);

-- Edit Plans Table: Stores candidate reel segments generated by AI.
create table if not exists edit_plans (
    id uuid primary key default gen_random_uuid(),
    video_id uuid references videos(id) on delete cascade,
    candidate_index integer not null,
    segments jsonb not null,
    status text not null,
    hook_score float,
    overall_score float,
    feedback text,
    created_at timestamp with time zone default current_timestamp
);

-- Reels Table: Stores final output clips.
create table if not exists reels (
    id uuid primary key default gen_random_uuid(),
    video_id uuid references videos(id) on delete cascade,
    edit_plan_id uuid references edit_plans(id),
    storage_path text not null,
    public_url text,
    title text,
    meta jsonb default '{}'::jsonb,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);

-- Jobs Table: Pipeline orchestration and heartbeat tracking.
create table if not exists jobs (
    id uuid primary key default gen_random_uuid(),
    video_id uuid references videos(id) on delete cascade,
    current_stage text not null,
    status text not null,
    last_error text,
    retry_count int default 0,
    started_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);

-- -------------------------------------------------------------
-- 2. Constraints & Uniqueness
-- -------------------------------------------------------------

-- Ensure one transcript per video.
create unique index if not exists uq_transcripts_video_id on transcripts (video_id);

-- Ensure one job row per video (used for on_conflict=video_id upserts).
create unique index if not exists uq_jobs_video_id on jobs (video_id);

-- Status / Stage Check Constraints
alter table videos drop constraint if exists videos_status_check;
alter table videos add constraint videos_status_check
  check (status in ('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED'));

alter table jobs drop constraint if exists jobs_status_check;
alter table jobs add constraint jobs_status_check
  check (status in ('PENDING', 'RUNNING', 'READY', 'FAILED', 'PERMANENTLY_FAILED'));

alter table jobs drop constraint if exists jobs_current_stage_check;
alter table jobs add constraint jobs_current_stage_check
  check (current_stage in ('PENDING', 'VALIDATING', 'TRANSCRIBING_PLANNING', 'REVIEWING', 'RENDERING', 'READY'));

alter table edit_plans drop constraint if exists edit_plans_status_check;
alter table edit_plans add constraint edit_plans_status_check
  check (status in ('pending_review', 'accepted', 'rejected'));

-- -------------------------------------------------------------
-- 3. Indexes (Performance)
-- -------------------------------------------------------------
create index if not exists idx_videos_user_id        on videos (user_id);
create index if not exists idx_videos_expires_at     on videos (expires_at);
create index if not exists idx_transcripts_video_id  on transcripts (video_id);
create index if not exists idx_edit_plans_video_id   on edit_plans (video_id, status);
create index if not exists idx_reels_video_id        on reels (video_id);
create index if not exists idx_jobs_video_id         on jobs (video_id, started_at desc);

-- -------------------------------------------------------------
-- 4. Row Level Security (RLS)
-- -------------------------------------------------------------
alter table videos     enable row level security;
alter table transcripts enable row level security;
alter table edit_plans enable row level security;
alter table reels      enable row level security;
alter table jobs       enable row level security;

drop policy if exists "Users can manage their own videos"      on videos;
drop policy if exists "Users can manage their own transcripts" on transcripts;
drop policy if exists "Users can manage their own edit plans"  on edit_plans;
drop policy if exists "Users can manage their own reels"       on reels;
drop policy if exists "Users can manage their own jobs"        on jobs;

create policy "Users can manage their own videos" on videos for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage their own transcripts" on transcripts for all
  using (exists (select 1 from videos v where v.id = transcripts.video_id and v.user_id = auth.uid()));

create policy "Users can manage their own edit plans" on edit_plans for all
  using (exists (select 1 from videos v where v.id = edit_plans.video_id and v.user_id = auth.uid()));

create policy "Users can manage their own reels" on reels for all
  using (exists (select 1 from videos v where v.id = reels.video_id and v.user_id = auth.uid()));

create policy "Users can manage their own jobs" on jobs for all
  using (exists (select 1 from videos v where v.id = jobs.video_id and v.user_id = auth.uid()));

-- -------------------------------------------------------------
-- 5. Storage Policies ('reels-videos' bucket)
-- -------------------------------------------------------------
drop policy if exists "Public read reels-videos" on storage.objects;
create policy "Public read reels-videos" on storage.objects for select
  using (bucket_id = 'reels-videos');

drop policy if exists "Owner upload reels-videos" on storage.objects;
create policy "Owner upload reels-videos" on storage.objects for insert
  with check (
    bucket_id = 'reels-videos'
    and auth.role() = 'authenticated'
    and auth.uid()::text = split_part(name, '/', 1)
  );

drop policy if exists "Owner update reels-videos" on storage.objects;
create policy "Owner update reels-videos" on storage.objects for update
  using (bucket_id = 'reels-videos' and auth.uid()::text = split_part(name, '/', 1))
  with check (bucket_id = 'reels-videos' and auth.uid()::text = split_part(name, '/', 1));

drop policy if exists "Owner delete reels-videos" on storage.objects;
create policy "Owner delete reels-videos" on storage.objects for delete
  using (bucket_id = 'reels-videos' and auth.uid()::text = split_part(name, '/', 1));

-- -------------------------------------------------------------
-- 6. Automation (Triggers)
-- -------------------------------------------------------------
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = current_timestamp;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_videos_updated_at on videos;
create trigger trg_videos_updated_at before update on videos
  for each row execute function set_updated_at();

drop trigger if exists trg_reels_updated_at on reels;
create trigger trg_reels_updated_at before update on reels
  for each row execute function set_updated_at();

drop trigger if exists trg_jobs_updated_at on jobs;
create trigger trg_jobs_updated_at before update on jobs
  for each row execute function set_updated_at();
